CREATE TABLE [dbo].[UserState](
	[Id] [tinyint] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](10) NOT NULL,
 CONSTRAINT [PK_UserStatus] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Role](
	[Id] [tinyint] NOT NULL,
	[RoleName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Gender]
(
	[ID] TINYINT NOT NULL,
	[NAME] VARCHAR(50) NOT NULL
 CONSTRAINT [PK_Gender] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY] 
GO

CREATE TABLE [dbo].[User]
(
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Password] [nvarchar](128) NOT NULL,
	[Firstname] [nvarchar](100) NOT NULL,
	[Lastname] [nvarchar](100) NOT NULL,
	[Avatar] [VARCHAR](500) NOT NULL,
	[GenderId] [tinyint] NOT NULL,
	[RoleId] [tinyint] NOT NULL,
	[StatusId] [tinyint] NOT NULL,
	[IsDeleted] [BIT] NOT NULL,
	[LastLoginDate] [datetime] NULL,
	[LastPasswordChangedDate] [datetime] NULL,
	[ForgotPasswordToken] [VARCHAR](500) NOT NULL,
	[ForgotPasswordTokenSentOn] [DATETIME] NOT NULL,
	[CreatedBy] [UNIQUEIDENTIFIER] NOT NULL,
	[CreatedOn] [DATETIME] NOT NULL,
	[ModifiedBy] [UNIQUEIDENTIFIER] NOT NULL,
	[ModifiedOn] [DATETIME] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[User] ADD  CONSTRAINT [DF_User_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
ALTER TABLE [dbo].[User] ADD  CONSTRAINT [DF_User_CreatedOn]  DEFAULT ((GETADET())) FOR [CreatedOn]
GO

ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_Client_UserState] FOREIGN KEY([StatusId]) REFERENCES [dbo].[UserState] ([Id])
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_Client_Role] FOREIGN KEY([RoleId]) REFERENCES [dbo].[Role] ([Id])
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_Client_Gender] FOREIGN KEY([GenderId]) REFERENCES [dbo].[Gender] ([Id])
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_CreatedBy] FOREIGN KEY([CreatedBy]) REFERENCES [dbo].[User] ([Id])
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_ModifiedBy] FOREIGN KEY([ModifiedBy]) REFERENCES [dbo].[User] ([Id])
GO

CREATE TABLE [dbo].[Game](
	[Id] [tinyint] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](10) NOT NULL,
 CONSTRAINT [PK_Game] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Tournament](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](10) NOT NULL,
	[GameId] [tinyint] NOT NULL,
 CONSTRAINT [PK_Tournament] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Tournament]  WITH CHECK ADD  CONSTRAINT [FK_Tournament_GameId] FOREIGN KEY([GameId]) REFERENCES [dbo].[Game] ([Id])
GO

CREATE TABLE [dbo].[Subdivision](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[Name] [VARCHAR](10) NOT NULL,
	[TournamentId] [INT] NOT NULL,
 CONSTRAINT [PK_Subdivision] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Subdivision]  WITH CHECK ADD  CONSTRAINT [FK_Subdivision_TournamentId] FOREIGN KEY([TournamentId]) REFERENCES [dbo].[Tournament] ([Id])
GO

CREATE TABLE [dbo].[Team](
	[Id] [BIGNIT] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](10) NOT NULL,
	[SubdivisionId] [INT] NOT NULL,
 CONSTRAINT [PK_Team] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Team]  WITH CHECK ADD  CONSTRAINT [FK_Team_SubdivisionId] FOREIGN KEY([SubdivisionId]) REFERENCES [dbo].[Subdivision] ([Id])
GO

CREATE TABLE [dbo].[Participant](
	[Id] [BIGNIT] IDENTITY(1,1) NOT NULL,
	[UserId] [UNIQUEIDENTIFIER] NOT NULL,
	[SubdivisionId] [INT] NOT NULL,
 CONSTRAINT [PK_Participant] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Participant]  WITH CHECK ADD  CONSTRAINT [FK_Participant_User] FOREIGN KEY([UserId]) REFERENCES [dbo].[User] ([Id])
ALTER TABLE [dbo].[Participant]  WITH CHECK ADD  CONSTRAINT [FK_Participant_Subdivision] FOREIGN KEY([SubdivisionId]) REFERENCES [dbo].[Subdivision] ([Id])
GO

CREATE TABLE [dbo].[TeamParticipant](
	[Id] [BIGNIT] IDENTITY(1,1) NOT NULL,
	[TeamId] [BIGNIT] NOT NULL,
	[ParticipantId] [BIGNIT] NOT NULL,
 CONSTRAINT [PK_TeamParticipant] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TeamParticipant]  WITH CHECK ADD  CONSTRAINT [FK_TeamParticipant_Team] FOREIGN KEY([TeamId]) REFERENCES [dbo].[Team] ([Id])
ALTER TABLE [dbo].[TeamParticipant]  WITH CHECK ADD  CONSTRAINT [FK_TeamParticipant_Participant] FOREIGN KEY([ParticipantId]) REFERENCES [dbo].[Participant] ([Id])
GO

CREATE TABLE [dbo].[Stage](
	[Id] [BIGNIT] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](10) NOT NULL,
	[SubdivisionId] [INT] NOT NULL,
 CONSTRAINT [PK_Stage] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Stage]  WITH CHECK ADD  CONSTRAINT [FK_Stage_Subdivision] FOREIGN KEY([SubdivisionId]) REFERENCES [dbo].[Subdivision] ([Id])
GO

CREATE TABLE [dbo].[Match](
	[Id] [BIGNIT] IDENTITY(1,1) NOT NULL,
	[StageId] [BIGNIT] NOT NULL,
	[Team1Id] [BIGNIT] NOT NULL,
	[Team2Id] [BIGNIT] NOT NULL,
	[ScheduledDate] [DATETIME] NOT NULL,
	[WinnerTeamId] [BIGNIT] NULL,
 CONSTRAINT [PK_Match] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Match]  WITH CHECK ADD  CONSTRAINT [FK_Match_Stage] FOREIGN KEY([StageId]) REFERENCES [dbo].[Stage] ([Id])
ALTER TABLE [dbo].[Match]  WITH CHECK ADD  CONSTRAINT [FK_Match_Team] FOREIGN KEY([Team1Id]) REFERENCES [dbo].[Team] ([Id])
ALTER TABLE [dbo].[Match]  WITH CHECK ADD  CONSTRAINT [FK_Match_Team1] FOREIGN KEY([Team2Id]) REFERENCES [dbo].[Team] ([Id])
ALTER TABLE [dbo].[Match]  WITH CHECK ADD  CONSTRAINT [FK_Match_Team2] FOREIGN KEY([WinnerTeamId]) REFERENCES [dbo].[Team] ([Id])
GO

CREATE TABLE [dbo].[Score](
	[Id] [BIGNIT] IDENTITY(1,1) NOT NULL,
	[Team1SetScore] [TINYINT] NOT NULL,
	[Team2SetScore] [TINYINT] NOT NULL,
	[WinnerTeamId] [BIGNIT] NULL,
 CONSTRAINT [PK_Score] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Score]  WITH CHECK ADD  CONSTRAINT [FK_Score_Team] FOREIGN KEY([WinnerTeamId]) REFERENCES [dbo].[Team] ([Id])
GO
