//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentOrganizer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public long Id { get; set; }
        public long StageId { get; set; }
        public long Team1Id { get; set; }
        public long Team2Id { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public Nullable<long> WinnerTeamId { get; set; }
    
        public virtual Stage Stage { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Team Team2 { get; set; }
    }
}
